#!/usr/bin/env zsh

# ZSHENV AWS
#
#

# This requires to have https://github.com/otype/aws-helpers installed
function aig() {
  PARAMS=$*
  EGREP_PARAMS=$(echo $PARAMS | sed 's/ /|/g')
  aws-instances | egrep "($EGREP_PARAMS)"
}
