#!/usr/bin/env zsh

# ZSHENV HOMEBREW
#
# NOTE: POTENTIALLY OUTDATED!!!
#

if [[ `uname -s` == "Darwin" ]]; then
    # Added for brew zsh-completions
    if [[ `alias | grep "^run-help"` ]]; then
	unalias run-help
	autoload run-help
	HELPDIR=/usr/local/share/zsh/helpfiles
    fi

    export PATH=/usr/local/bin:/usr/local/sbin:$PATH

    # Aliases
    alias buuc="brew update && brew upgrade && brew cleanup"
fi
