#!/usr/local/bin/zsh

# ZSHENV PYENV
#
#
if [[ -d "/usr/local/opt/pyenv" ]]; then
    export PYENV_ROOT="/usr/local/opt/pyenv"
    export PATH="$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH"
    if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
fi
