#!/usr/local/bin/zsh

# ZSHENV Mysql
#
# Run `brew install mysql@5.7` to install!
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"

# For compilers to find mysql@5.7 you may need to set:
export LDFLAGS="${LDFLAGS} -L/usr/local/opt/mysql@5.7/lib"
export CPPFLAGS="${CPPFLAGS} -I/usr/local/opt/mysql@5.7/include"

# For pkg-config to find mysql@5.7 you may need to set:
export PKG_CONFIG_PATH="${PKG_CONFIG_PATH} /usr/local/opt/mysql@5.7/lib/pkgconfig"
