#!/usr/bin/env zsh

# TILIX (Pop OS/Ubuntu terminal emulator)
#
#

# Work with Tilix (Linux/Ubuntu)
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
   source /etc/profile.d/vte.sh
fi

# To make Tilix Profile switching possible
source /usr/share/tilix/scripts/tilix_int.sh
