#!/usr/bin/env zsh

# ZSHENV JAVA
#
#

# Print out all Java processes
function pj() {
    ps aux | grep "$JAVA_HOME" | grep -v "grep" | awk '{print $2, $11, $(NF)}'
}

# Kill all Java processes
function pjk() {
    for pid in `pj | awk '{print $1}'`
    do
	      echo ">>> Killing [$pid]"
	      kill -9 $pid
    done
}

function show-java-versions() {
    update-java-alternatives -l
}

function switch-to-java() {
    if [[ -z "$1" ]]; then
        show-java-versions
        return 1
    fi

    jdk_version=$1

    export JAVA_HOME="/usr/lib/jvm/java-${jdk_version}-openjdk-amd64"
    sudo update-java-alternatives --config java
    sudo update-java-alternatives --config javac
    # echo "JAVA_HOME=\"/usr/lib/jvm/java-${jdk_version}-openjdk-amd64\"" | sudo tee -a /etc/environment
}

# function switch-to-java-on-mac() {
#     jdk=$1

#     if [[ "$jdk" == "1.8" ]]; then
# 	      JAVA_HOME=$JDK8
#     elif [[ "$jdk" == "9" ]]; then
# 	      JAVA_HOME=$JDK9
#     else
# 	      JAVA_HOME=`/usr/libexec/java_home -v $jdk`
#     fi

#     export JAVA_HOME
#     echo "Switching to $JAVA_HOME"
#     # set-maven-opts
#     # echo "Setting MAVEN_OPTS=$MAVEN_OPTS"
# }

# Fix IntelliJ 12+ vmoptions when upgrading
# See more details here:
# https://intellij-support.jetbrains.com/hc/en-us/articles/206544869-Configuring-JVM-options-and-platform-properties
function fix-intellij-vmoptions() {
    if [[ "`uname -s`" == "FreeBSD" ]]; then
	      echo "No config, yet! Exiting now!"
	      exit 1
    elif [[ `uname -s` = "Linux" ]]; then
	      echo "No config, yet! Exiting now!"
	      exit 1
    else
	      intellij_pref_path="${HOME}/Library/Preferences/IntelliJIdea2016.1"
    fi

    idea_vmoptions_file="${intellij_pref_path}/idea.vmoptions"

    mkdir -p $intellij_pref_path
    echo "[Writing new configuration]"
    cat << EOF > ${idea_vmoptions_file}
-server
-Xms256m
-Xmx2048m
-XX:ReservedCodeCacheSize=300m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:MaxJavaStackTraceDepth=-1
EOF
    echo ""
    echo "Following file was written:"
    echo "${idea_vmoptions_file}"
    echo ""
    cat $idea_vmoptions_file

    echo ""
    echo "Done. Restart IntelliJ for changes to take effect."
    return 0
}

# JDKs
#
#
if [[ `uname -s` = "Linux" ]]; then
    # do nothing
    export JAVA_HOME="/usr/lib/jvm/java-16-openjdk-amd64"
else # For Mac
    export JDK8=`/usr/libexec/java_home -v 1.8`
    export JDK9=`/usr/libexec/java_home -v 9`
    defaultJDK=$JDK8
    export JAVA_HOME="${defaultJDK}"
    export JRE_HOME="${defaultJDK}/jre"
fi
