#!/usr/bin/env zsh

# ZSHENV General
#
#

# Enable Emacs mode
bindkey -e

# Unblock ^S (normally captured for XON/XOFF flow control) so it can be used for forward history search
[[ -t 0 ]] && stty -ixon

# ^R is already the default in Emacs mode; ^S needs stty -ixon above to work
bindkey "^S" history-incremental-search-forward

# Preferred editor: emacsclient if available (this will be set in zshenv-emacs), otherwise vim.
[[ -f $(which emacsclient) ]] || export EDITOR="vim"

# General
alias h=history
alias sl=ls

# Calculator should use higher precision (no rounding)
alias bc="bc -l"

# VI
alias vi=vim

# NO_PROXY
# Ignored hosts lists from Gnome can be extracted with:
# $ gsettings get org.gnome.system.proxy ignore-hosts
NO_PROXY="localhost, 127.0.0.1/8, 0.0.0.0, ::1, maps.google.com, revolut.com, 10.200.0.0/16, content-discovery-service-mcp.k8s-cobalt.internal.azure.meltwater.io"
export NO_PROXY
