#!/usr/bin/env zsh

# ZSHENV PYENV
#
#

if [[ -d "/usr/local/opt/pyenv" ]]; then
    # For Mac OS X
    export PYENV_ROOT="/usr/local/opt/pyenv"
    export PATH="$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH"
    if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
elif [[ -d "$HOME/.pyenv/" ]]; then
    # For Linux
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
