#!/usr/bin/env zsh

# ZHENV ANDROID SDK
#
#
if [[ -d "/usr/local/Cellar/android-sdk" ]]; then
	ANDROID_SDK_ROOT=/usr/local/Cellar/android-sdk/`ls /usr/local/Cellar/android-sdk`
	export ANDROID_SDK_ROOT
        ANDROID_HOME=$ANDROID_SDK_ROOT
        export ANDROID_HOME
fi
