#!/usr/bin/env zsh

# TILIX
#
# Tilix is an advanced GTK3 tiling terminal emulator that follows the Gnome Human Interface Guidelines.
# https://gnunn1.github.io/tilix-web/

# Work with Tilix (Linux/Ubuntu)
if [[ $TILIX_ID ]] || [[ $VTE_VERSION ]]; then
   source /etc/profile.d/vte.sh
fi

# To make Tilix Profile switching possible
[[ -f `which tilix` ]] && source /usr/share/tilix/scripts/tilix_int.sh
