#!/usr/bin/env zsh

# ZSHENV RBENV
#
#

if [[ -d "$HOME/.rbenv" ]]; then
	  # On Linux (watch out if this clashes with Mac installations)
	  eval "$(~/.rbenv/bin/rbenv init - --no-rehash)"
	  ~/.rbenv/bin/rbenv rehash
fi

# If you use "gem install --user <gem_name>" with the "system"-ruby version ...
# Update this path to match your current system ruby version if needed.

# Aliases
alias be="bundle exec"
alias ber="bundle exec rake"
alias bi="bundle install"
