#!/usr/bin/env zsh

# ZSHENV ASDF
#
#
# For Mac OS X
[[ -d "/usr/local/opt/asdf" ]] && source /usr/local/opt/asdf/asdf.sh

# For Ubuntu/Pop OS
[[ -f "$HOME/.asdf/asdf.sh" ]] && source $HOME/.asdf/asdf.sh
