#!/usr/bin/env zsh

# ZSHENV Emacs
#
#

# The emacs daemon can be started automatically in a very simple manner:
# When you invoke emacsclient -t/-c the server will be started (with emacs --daemon) if it's not already running.
export ALTERNATE_EDITOR=""

# $EDITOR should open in terminal
export EDITOR="emacsclient -t"

# $VISUAL opens in GUI with non-daemon as alternate
export VISUAL="emacsclient -c -a emacs"

# Aliases
alias e="emacsclient -t"
alias ec="emacsclient -c"
