#!/usr/bin/env zsh

# ZSHENV JAVA
#
#

# Print out all Java processes
function pj() {
    ps aux | grep "$JAVA_HOME" | grep -v "grep" | awk '{print $2, $11, $(NF)}'
}

# Kill all Java processes
function pjk() {
    for pid in `pj | awk '{print $1}'`
    do
	echo ">>> Killing [$pid]"
	kill -9 $pid
    done
}

function show-java-versions() {
    update-alternatives --list | grep jdk
}

function switch-to-java() {
    sudo update-alternatives --config java_sdk_openjdk
    sudo update-alternatives --config java
    sudo update-alternatives --config javac

    echo "\n>>> java -version"
    java -version

    echo "\n>>> javac -version"
    javac -version

    echo "\n>>> mvn -version"
    mvn -version
}
