#!/usr/bin/env zsh

# ZSHENV PYTHON
#
#

if [[ `uname -s` == "Darwin" ]]; then
    [[ -d "/usr/local/share/python" ]] && export PATH=/usr/local/share/python:$PATH
elif [[ $OSTYPE == 'linux-gnu' ]]; then
    [[ -d "$(python -m site --user-base)/bin" ]] && export PATH="$(python -m site --user-base)/bin:$PATH"
fi
