#!/usr/bin/env zsh

# ZSHENV GOENV
#
# goenv (https://github.com/syndbg/goenv)
if [[ $OSTYPE == 'darwin' ]]; then
    if [[ -f "/usr/local/bin/goenv" ]]; then
	export GOENV_ROOT="$HOME/.goenv"
	export PATH="$GOENV_ROOT/bin:$PATH"
	eval "$(goenv init -)"
	export PATH="$GOROOT/bin:$PATH"
	export PATH="$PATH:$GOPATH/bin"
    fi
elif [[ $OSTYPE == 'linux-gnu' ]]; then
    if [[ -f "$HOME/.goenv/bin/goenv" ]]; then
	export GOENV_ROOT="$HOME/.goenv"
	export PATH="$GOENV_ROOT/bin:$PATH"
	eval "$(goenv init -)"
	export PATH="$GOROOT/bin:$PATH"
	export PATH="$PATH:$GOPATH/bin"
    fi
fi
