#!/usr/bin/env zsh

# ZHENV ANDROID SDK
#
#
if [[ -d "/usr/local/Cellar/android-sdk" ]]; then
    # For MAC:
    export ANDROID_SDK_ROOT=/usr/local/Cellar/android-sdk/`ls /usr/local/Cellar/android-sdk`
    export ANDROID_HOME=$ANDROID_SDK_ROOT
elif [[ -d "$HOME/Android/Sdk/" ]]; then
    # For Linux/Fedora
    export ANDROID_HOME="~/Android/Sdk"
    export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools"
fi
