#!/usr/bin/env zsh

# ZSHENV JAVA
#
#

# Print out all Java processes
function pj() {
    ps aux | grep "$JAVA_HOME" | grep -v "grep" | awk '{print $2, $11, $(NF)}'
}

# Kill all Java processes
function pjk() {
    for pid in `pj | awk '{print $1}'`
    do
	      echo ">>> Killing [$pid]"
	      kill -9 $pid
    done
}

function show-java-versions() {
    update-alternatives --list | grep jdk
}

function switch-to-java() {
    sudo update-alternatives --config java_sdk_openjdk
    sudo update-alternatives --config java
    sudo update-alternatives --config javac

    echo "\n>>> java -version"
    java -version

    echo "\n>>> javac -version"
    javac -version

    echo "\n>>> mvn -version"
    mvn -version
}


# JDKs
#
#
if [[ `uname -s` = "Linux" ]]; then
    # do nothing
    export JAVA_HOME="/usr/lib/jvm/java-16-openjdk-amd64"
else # For Mac
    export JDK8=`/usr/libexec/java_home -v 1.8`
    defaultJDK=$JDK8
    export JAVA_HOME="${defaultJDK}"
    export JRE_HOME="${defaultJDK}/jre"
fi
