#!/usr/bin/env zsh

# ZSHENV RBENV
#
#

if [[ -d "$HOME/.rbenv" ]]; then
	  # On Linux (watch out if this clashes with Mac installations)
	  eval "$(~/.rbenv/bin/rbenv init - --no-rehash)"
	  ~/.rbenv/bin/rbenv rehash
fi

# If you use "gem install --user <gem_name>" with the "system"-ruby version ...
[[ -d "$HOME/.gem/ruby/2.0.0/bin" ]] && export PATH="$HOME/.gem/ruby/2.0.0/bin:$PATH"

# Aliases
alias be="bundle exec"
alias ber="bundle exec rake"
alias bi="bundle install"
