#!/usr/bin/env zsh

# ZSHENV GOENV
#
#

# This requires goenv (https://github.com/syndbg/goenv) to be installed.
if [[ -f "/usr/local/bin/goenv" ]] || [[ -f "$HOME/.goenv/bin/goenv" ]]; then
    export GOENV_ROOT="$HOME/.goenv"
    export PATH="$GOENV_ROOT/bin:$PATH"
    eval "$(goenv init -)"

    # We simply put GOPATH to $HOME ... this will create:
    #   - ~/src (exists anyway),
    #   - ~/pkg and
    #   - ~/bin (which actually already is part of env PATH).
    export GOPATH=$HOME
    export PATH="$GOROOT/bin:$PATH"
    export PATH="$PATH:$GOPATH/bin"
fi
