#!/usr/bin/env zsh

# ZSHENV ASDF
#
#
[[ -f "$HOME/.asdf/asdf.sh" ]] && source $HOME/.asdf/asdf.sh

# append asdf completions to fpath (compinit is called once in zshrc)
fpath=(${ASDF_DIR}/completions $fpath)
