#!/usr/bin/env zsh

# ZHENV ANDROID SDK
#
#

if [[ -d "$HOME/Android/Sdk/" ]]; then
	  export ANDROID_HOME="~/Android/Sdk"
	  export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools"
fi
