#!/usr/bin/env zsh

# ZSHENV RBENV
#
#

# On Mac OS X
if [[ -d "/usr/local/var/rbenv" ]]; then
    export RBENV_ROOT=/usr/local/var/rbenv
    if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
    rbenv rehash
fi

# On Linux (watch out if this clashes with Mac installations)
if [[ -d "$HOME/.rbenv" ]]; then
    eval "$(~/.rbenv/bin/rbenv init -)"
    ~/.rbenv/bin/rbenv rehash
fi

# If you use "gem install --user <gem_name>" with the "system"-ruby version ...
[[ -d "$HOME/.gem/ruby/2.0.0/bin" ]] && export PATH="$HOME/.gem/ruby/2.0.0/bin:$PATH"

# Aliases
alias be="bundle exec"
alias ber="bundle exec rake"
alias bi="bundle install"
