#!/usr/local/bin/zsh

# ZPROFILE
#
# If configured it will use gpg-agent as SSH agent (for smart keys)
#
if [[ -f "$HOME/.gnupg/gpg-agent.conf" ]]; then
    cat $HOME/.gnupg/gpg-agent.conf | grep enable-ssh-support > /dev/null
    ssh_support_enabled=$?

    if [[ $ssh_support_enabled -eq 0 ]]; then
	gpgconf --kill gpg-agent
	gpg-agent --options ~/.gnupg/gpg-agent.conf --daemon

	export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
	launchctl setenv SSH_AUTH_SOCK $SSH_AUTH_SOCK

	GPG_TTY=$(tty)
	export GPG_TTY
    fi
fi
